# ============================================================
# LANDGUARD AI
# Context-Aware Recommendation Engine
#
# V1:
# - Existing project snapshots only
# - Risk-aware
# - Snapshot-aware
# - Risk-DNA-aware
# - Deterministic intervention rules
#
# IMPORTANT:
# SHAP explains model behavior.
# Rules translate observed conditions into actions.
# Recommendations are NOT causal conclusions.
# ============================================================

from typing import Any, Dict, List, Optional


# ============================================================
# HELPERS
# ============================================================

def _get(project: Dict[str, Any], *names, default=None):
    """
    Return the first available field.
    Supports both V1 naming variants.
    """

    for name in names:

        if name in project:

            value = project[name]

            if value is None:
                continue

            return value

    return default


def _float(project: Dict[str, Any], *names, default=0.0):

    value = _get(
        project,
        *names,
        default=default
    )

    try:
        return float(value)

    except Exception:
        return default


def _int(project: Dict[str, Any], *names, default=0):

    value = _get(
        project,
        *names,
        default=default
    )

    try:
        return int(float(value))

    except Exception:
        return default


def _bool(project: Dict[str, Any], *names, default=False):

    value = _get(
        project,
        *names,
        default=default
    )

    if isinstance(value, bool):
        return value

    if isinstance(value, str):

        return value.strip().lower() in {
            "true",
            "1",
            "yes",
            "y",
            "active",
        }

    try:
        return bool(value)

    except Exception:
        return default


def _text(project: Dict[str, Any], *names, default=""):

    value = _get(
        project,
        *names,
        default=default
    )

    if value is None:
        return default

    return str(value)


# ============================================================
# RISK-DNA MATCHING
# ============================================================

def _driver_matches(
    risk_dna: Optional[List[Dict[str, Any]]],
    keywords
):
    """
    Returns True if Risk DNA contains a driver related
    to the supplied keywords.
    """

    if not risk_dna:
        return False

    for driver in risk_dna:

        feature = str(
            driver.get("feature", "")
        ).lower()

        raw_feature = str(
            driver.get("raw_feature", "")
        ).lower()

        combined = feature + " " + raw_feature

        for keyword in keywords:

            if keyword.lower() in combined:
                return True

    return False


# ============================================================
# MAIN ENGINE
# ============================================================

def generate_recommendations(
    project: Dict[str, Any],
    probability: Optional[float] = None,
    risk_level: Optional[str] = None,
    risk_dna: Optional[List[Dict[str, Any]]] = None,
):
    """
    Generate context-aware recommendations.

    Parameters
    ----------
    project:
        Exact current project snapshot.

    probability:
        Model delay probability, 0-1.

    risk_level:
        LOW / MEDIUM / HIGH.

    risk_dna:
        Top SHAP drivers generated by the app.

    Returns
    -------
    List[dict]
        Each recommendation contains:
        title
        description
        priority
        driver
    """

    # --------------------------------------------------------
    # NORMALIZE RISK
    # --------------------------------------------------------

    if probability is not None:

        try:
            probability = float(probability)

        except Exception:
            probability = None

    if risk_level:

        risk_level = str(
            risk_level
        ).upper()

    elif probability is not None:

        if probability >= 0.70:
            risk_level = "HIGH"

        elif probability >= 0.45:
            risk_level = "MEDIUM"

        else:
            risk_level = "LOW"

    else:

        risk_level = "LOW"

    # --------------------------------------------------------
    # LOW RISK
    # --------------------------------------------------------

    if risk_level == "LOW":

        return [
            {
                "title": "Continue Routine Monitoring",
                "description": (
                    "Current model risk is below the intervention "
                    "threshold. No specific intervention is "
                    "recommended from the current snapshot."
                ),
                "priority": "Low",
                "driver": "Overall delay risk",
            }
        ]

    recommendations = []

    # ========================================================
    # 1. LAND TITLE CLARITY
    # ========================================================

    title_clarity = _float(
        project,
        "percent_land_clear_title",
        default=100.0
    )

    disputed_ownership = _float(
        project,
        "percent_land_disputed_ownership",
        default=0.0
    )

    title_driver = _driver_matches(
        risk_dna,
        [
            "title",
            "ownership",
            "land title",
            "disputed",
        ],
    )

    if (
        title_clarity < 70
        or disputed_ownership >= 20
        or title_driver
    ):

        priority = (
            "High"
            if title_clarity < 60
            or disputed_ownership >= 30
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Improve Land Title Clarity",
                "description": (
                    f"Only {title_clarity:.0f}% of land has "
                    f"clear title and {disputed_ownership:.0f}% "
                    "is flagged with disputed ownership. "
                    "Prioritize title verification, ownership "
                    "reconciliation and unresolved parcel review."
                ),
                "priority": priority,
                "driver": "Land Title Clarity",
            }
        )

    # ========================================================
    # 2. STAGE DELAY
    # ========================================================

    stage_delay = _float(
        project,
        "cumulative_stage_delay_days_as_of_snapshot",
        default=0.0
    )

    stage_driver = _driver_matches(
        risk_dna,
        [
            "stage delay",
            "accumulated stage delay",
            "cumulative stage delay",
            "acquisition duration",
            "planned acquisition duration",
        ],
    )

    if (
        stage_delay >= 60
        or stage_driver
    ):

        priority = (
            "High"
            if stage_delay >= 120
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Recover Accumulated Stage Delay",
                "description": (
                    f"The current snapshot shows approximately "
                    f"{stage_delay:.0f} days of accumulated stage "
                    "delay. Review the delayed milestones, identify "
                    "the active bottleneck and assign a recovery "
                    "owner with a target date."
                ),
                "priority": priority,
                "driver": "Accumulated Stage Delay",
            }
        )

    # ========================================================
    # 3. CRITICAL APPROVALS
    # ========================================================

    pending_approvals = _int(
        project,
        "approvals_pending_count",
        default=0
    )

    critical_pending = _bool(
        project,
        "critical_approval_pending_flag",
        default=False
    )

    approval_driver = _driver_matches(
        risk_dna,
        [
            "approval",
            "pending approval",
        ],
    )

    if (
        critical_pending
        or pending_approvals > 0
        or approval_driver
    ):

        priority = (
            "High"
            if critical_pending
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Escalate Pending Approval Bottlenecks",
                "description": (
                    f"{pending_approvals} approval(s) are currently "
                    "pending. Review critical-path approvals and "
                    "escalate those exceeding their expected "
                    "processing timeline."
                ),
                "priority": priority,
                "driver": "Pending Approvals",
            }
        )

    # ========================================================
    # 4. COMPENSATION
    # ========================================================

    compensation = _float(
        project,
        "percent_compensation_disbursed_as_of_snapshot",
        "percent_disbursed",
        default=100.0
    )

    compensation_dispute = _bool(
        project,
        "compensation_dispute_flag",
        default=False
    )

    compensation_driver = _driver_matches(
        risk_dna,
        [
            "compensation",
            "disbursement",
        ],
    )

    if (
        compensation < 70
        or compensation_dispute
        or compensation_driver
    ):

        priority = (
            "High"
            if compensation < 50
            or compensation_dispute
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Accelerate Compensation Resolution",
                "description": (
                    f"Approximately {compensation:.0f}% of assessed "
                    "compensation has been disbursed. Review pending "
                    "beneficiaries, disputed amounts and payment "
                    "bottlenecks."
                ),
                "priority": priority,
                "driver": "Compensation Disbursement",
            }
        )

    # ========================================================
    # 5. LEGAL EXPOSURE
    # ========================================================

    legal_cases = _int(
        project,
        "active_legal_cases_count",
        "active_legal_cases_count_as_of_snapshot",
        default=0
    )

    stay_active = _bool(
        project,
        "stay_order_active_flag",
        "stay_order_active_flag_as_of_snapshot",
        default=False
    )

    legal_driver = _driver_matches(
        risk_dna,
        [
            "legal",
            "case",
            "stay",
        ],
    )

    if (
        legal_cases > 0
        or stay_active
        or legal_driver
    ):

        priority = (
            "High"
            if stay_active
            or legal_cases >= 3
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Monitor Legal Case Exposure",
                "description": (
                    f"{legal_cases} active legal case(s) are associated "
                    "with the current snapshot"
                    + (
                        ", including an active stay order."
                        if stay_active
                        else "."
                    )
                    + " Review their project impact and coordinate "
                    "with the appropriate legal authority."
                ),
                "priority": priority,
                "driver": "Legal Exposure",
            }
        )

    # ========================================================
    # 6. R&R / GRIEVANCES
    # ========================================================

    rr_backlog = _int(
        project,
        "rr_grievance_backlog_as_of_snapshot",
        "rr_grievances_filed",
        default=0
    )

    families_resettled = _float(
        project,
        "percent_families_resettled_as_of_snapshot",
        "percent_families_resettled",
        default=100.0
    )

    rr_approved = _bool(
        project,
        "rr_plan_approved_flag_as_of_snapshot",
        "rr_plan_approved_flag",
        default=True
    )

    rr_driver = _driver_matches(
        risk_dna,
        [
            "r&r",
            "rr grievance",
            "resettlement",
            "grievance",
            "displaced",
        ],
    )

    if (
        rr_backlog >= 5
        or families_resettled < 80
        or not rr_approved
        or rr_driver
    ):

        priority = (
            "High"
            if rr_backlog >= 10
            or families_resettled < 50
            or not rr_approved
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Clear R&R Grievance and Resettlement Backlog",
                "description": (
                    f"The snapshot shows {rr_backlog} unresolved "
                    "R&R grievance(s) and "
                    f"{families_resettled:.0f}% family resettlement "
                    "progress. Prioritize grievance resolution and "
                    "pending resettlement actions."
                ),
                "priority": priority,
                "driver": "R&R Progress",
            }
        )

    # ========================================================
    # 7. OFFICER CONTINUITY
    # ========================================================

    officer_turnover = _int(
        project,
        "officer_turnover_count_as_of_snapshot",
        "officer_turnover_count_last_year",
        default=0
    )

    officer_driver = _driver_matches(
        risk_dna,
        [
            "officer",
            "turnover",
            "administrative",
        ],
    )

    if (
        officer_turnover >= 3
        or officer_driver
    ):

        priority = (
            "High"
            if officer_turnover >= 5
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Stabilize Project Officer Continuity",
                "description": (
                    f"The project records approximately "
                    f"{officer_turnover} officer transition(s). "
                    "Maintain clear ownership, handover documentation "
                    "and continuity for critical acquisition decisions."
                ),
                "priority": priority,
                "driver": "Officer Continuity",
            }
        )

    # ========================================================
    # 8. PUBLIC OBJECTIONS
    # ========================================================

    objections = _int(
        project,
        "public_hearing_objections_count",
        default=0
    )

    objection_driver = _driver_matches(
        risk_dna,
        [
            "objection",
            "public",
            "stakeholder",
        ],
    )

    if (
        objections >= 10
        or objection_driver
    ):

        priority = (
            "High"
            if objections >= 25
            else "Medium"
        )

        recommendations.append(
            {
                "title": "Address Public Objection Backlog",
                "description": (
                    f"{objections} public-hearing objection(s) are "
                    "recorded. Review unresolved objections and "
                    "prioritize those affecting critical acquisition "
                    "milestones."
                ),
                "priority": priority,
                "driver": "Public Objections",
            }
        )

    # ========================================================
    # 9. FUNDING
    # ========================================================

    funding = _text(
        project,
        "funds_availability_status_as_of_snapshot",
        "funds_availability_status",
        default=""
    ).lower()

    funding_driver = _driver_matches(
        risk_dna,
        [
            "fund",
            "funding",
            "budget",
        ],
    )

    if (
        "insufficient" in funding
        or "shortage" in funding
        or "unavailable" in funding
        or funding_driver
    ):

        recommendations.append(
            {
                "title": "Resolve Funding Availability Constraint",
                "description": (
                    "The current snapshot indicates a funding "
                    "constraint. Review fund availability and "
                    "pending financial actions that could affect "
                    "land-acquisition milestones."
                ),
                "priority": "High",
                "driver": "Funding Availability",
            }
        )

    # ========================================================
    # REMOVE DUPLICATE DRIVER RECOMMENDATIONS
    # ========================================================

    unique = {}

    for rec in recommendations:

        key = (
            rec["title"]
            .strip()
            .lower()
        )

        unique[key] = rec

    recommendations = list(
        unique.values()
    )

    # ========================================================
    # SORT PRIORITY
    # ========================================================

    priority_order = {
        "High": 0,
        "Medium": 1,
        "Low": 2,
    }

    recommendations.sort(
        key=lambda x: priority_order.get(
            x.get("priority", "Low"),
            3
        )
    )

    # ========================================================
    # CAP OUTPUT
    # ========================================================

    if risk_level == "HIGH":

        recommendations = recommendations[:5]

    elif risk_level == "MEDIUM":

        recommendations = recommendations[:3]

    else:

        recommendations = recommendations[:1]

    # ========================================================
    # FALLBACK
    # ========================================================

    if not recommendations:

        recommendations.append(
            {
                "title": "Continue Targeted Monitoring",
                "description": (
                    "The project is above the intervention threshold, "
                    "but no specific rule was triggered by the current "
                    "snapshot. Review the Risk DNA and monitor the next "
                    "project update."
                ),
                "priority": "Medium",
                "driver": "Overall Risk",
            }
        )

    return recommendations


# ============================================================
# SIMPLE CLI TEST
# ============================================================

if __name__ == "__main__":

    example_project = {
        "percent_land_clear_title": 45,
        "percent_land_disputed_ownership": 35,
        "cumulative_stage_delay_days_as_of_snapshot": 240,
        "approvals_pending_count": 2,
        "critical_approval_pending_flag": True,
        "percent_compensation_disbursed_as_of_snapshot": 40,
        "compensation_dispute_flag": True,
        "active_legal_cases_count": 3,
        "stay_order_active_flag": True,
        "rr_grievance_backlog_as_of_snapshot": 12,
        "percent_families_resettled_as_of_snapshot": 55,
        "rr_plan_approved_flag_as_of_snapshot": False,
        "officer_turnover_count_as_of_snapshot": 5,
        "public_hearing_objections_count": 25,
        "funds_availability_status_as_of_snapshot": "Insufficient",
    }

    example_risk_dna = [
        {
            "feature": "Land Title Clarity",
            "raw_feature": "percent land clear title",
        },
        {
            "feature": "Accumulated Stage Delay",
            "raw_feature": "cumulative stage delay days",
        },
        {
            "feature": "Funding Availability",
            "raw_feature": "funds availability status",
        },
    ]

    result = generate_recommendations(
        example_project,
        probability=0.961,
        risk_level="HIGH",
        risk_dna=example_risk_dna,
    )

    print("\nLANDGUARD Recommendation Test\n")

    for i, rec in enumerate(
        result,
        start=1
    ):

        print(
            f"{i}. "
            f"[{rec['priority']}] "
            f"{rec['title']}"
        )

        print(
            f"   {rec['description']}"
        )

        print(
            f"   Driver: {rec['driver']}\n"
        )